[package]
name = "templater"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
extract-frontmatter = "4.1"
once_cell = "1.16"
pico-args = "0.5"
