[package]
name = "templater"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
extract-frontmatter = "2.1.0"
once_cell = "1.9.0"
